---

- name: Enable the flathub remote in the system installation
  community.general.flatpak_remote:
    name: flathub
    state: present
    enabled: true
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
  become: true
  become_user: root

- name: Install PrusaSlicer
  community.general.flatpak:
    name: com.prusa3d.PrusaSlicer
    state: present
    remote: flathub
  become: true
  become_user: root
